#!/usr/bin/env bash

# Initialize stack.
fin project start

# Run the common create script within the cli container.
fin exec bin/create.sh "$@"

# Repeat here just to show the site URL when we are done.
fin project start
